version: '3.3'
services:
  elasticsearch:
    container_name: elasticsearch
    build:
      context: ./elasticsearch
      args:
        - ELK_VERSION=${ELK_VERSION}
    restart: always
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=true"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=changeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ports:
      - "${ELASTICSEARCH_HTTP_PORT}:9200"
    networks:
      - elastic
  kibana:
    container_name: kibana
    build:
      context: ./kibana
      args:
        - ELK_VERSION=${ELK_VERSION}
    restart: always
    depends_on:
      - elasticsearch
    volumes: 
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "${KIBANA_HTTP_PORT}:5601"
    networks:
      - elastic

networks:
    elastic:
